---
apiVersion: v1
kind: Pod
metadata:
  name: iissample02
  labels:
    name: iissample02
spec:
  containers:
  - name: iissample02
    image: "easonlai/iissample02"
    ports:
    - containerPort: 80
  nodeSelector:
    beta.kubernetes.io/os: windows
