apiVersion: v1
kind: ReplicationController
metadata:
  name: iissample02
  labels:
    name: iissample02
    app: iissample02
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: iissample02
    spec:
      containers:
        - name: iissample02
          image: "easonlai/iissample02"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      nodeSelector:
        beta.kubernetes.io/os: windows
