apiVersion: v1
kind: Service
metadata:
  name: iissample02
  labels:
    name: iissample02
    app: iissample02
spec:
  selector:
    name: iissample02
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP