apiVersion: v1
kind: Service
metadata:
  name: iis-sample-01
  labels:
    name: iis-sample-01
    app: iis-sample-01
spec:
  selector:
    name: iis-sample-01
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP